### ISSUE TITLE
Option to prevent html entities in result

### ISSUE THREAD

**Issue by alcalyn** [Dreamseer/php-shorten#2]
When displaying a truncated text from this library with Twig, it displaying html entities because Twig safely encodes `&`.

Actually I expected UTF-8 characters are returned as is:

`truncateMarkup('<p>PHP éléphant</p>', 7)`

Expected:

`PHP élé...`

Actually:

`PHP &eacute;l&eacute;`

I understand this makes sense, but there should be a way to disable html entities, i.e by calling `html_entity_decode` on truncated text before returning it (which is what we are currently doing on our side).

**Comment by Dreamseer** [comment]
Good point, I’ll take a look into it!

**Comment by Dreamseer** [comment]
The latest version 3.0 handles UTF-8 characters (even Emoji) and does not convert them to entities.

I added some tests as well.

If you run into further problems feel free to re-open this issue.
